// Generated by Haxe 4.1.5
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
var Machine = function(initial) {
	this.transitions = new haxe_ds_StringMap();
	this.actions = new haxe_ds_StringMap();
	this.currentState = initial;
	this.processingEvent = false;
	this.cancellable = false;
	this.cancelled = false;
	this.pendingEvent = "";
	this.src = "";
	this.dst = "";
	this.evt = "";
};
Machine.__name__ = true;
Machine.prototype = {
	send: function(event) {
		if(this.cancelled) {
			return;
		}
		if(this.processingEvent) {
			this.pendingEvent = event;
			return;
		}
		this.src = this.currentState;
		this.evt = event;
		var ok = Object.prototype.hasOwnProperty.call(this.transitions.h,event + "###" + this.currentState);
		this.processingEvent = true;
		if(ok) {
			var nextState = this.transitions.h[event + "###" + this.currentState];
			this.dst = nextState;
			this.cancellable = true;
			var f = this.actions.h[">>" + event];
			if(f != null) {
				f();
			}
			if(this.cancelled) {
				this.processingEvent = false;
				this.cancellable = false;
				this.cancelled = false;
				this.pendingEvent = "";
				this.src = "";
				this.dst = "";
				this.evt = "";
				return;
			}
			f = this.actions.h[">>*"];
			if(f != null) {
				f();
			}
			if(this.cancelled) {
				this.processingEvent = false;
				this.cancellable = false;
				this.cancelled = false;
				this.pendingEvent = "";
				this.src = "";
				this.dst = "";
				this.evt = "";
				return;
			}
			f = this.actions.h["<" + this.currentState];
			if(f != null) {
				f();
			}
			if(this.cancelled) {
				this.processingEvent = false;
				this.cancellable = false;
				this.cancelled = false;
				this.pendingEvent = "";
				this.src = "";
				this.dst = "";
				this.evt = "";
				return;
			}
			f = this.actions.h["<*"];
			if(f != null) {
				f();
			}
			if(this.cancelled) {
				this.processingEvent = false;
				this.cancellable = false;
				this.cancelled = false;
				this.pendingEvent = "";
				this.src = "";
				this.dst = "";
				this.evt = "";
				return;
			}
			this.currentState = nextState;
			this.cancellable = false;
			f = this.actions.h[">" + this.currentState];
			if(f != null) {
				f();
			}
			f = this.actions.h[">*"];
			if(f != null) {
				f();
			}
			f = this.actions.h["<<" + event];
			if(f != null) {
				f();
			}
			f = this.actions.h["<<*"];
			if(f != null) {
				f();
			}
			this.dst = "";
		} else {
			var cnt = 0;
			var f = this.actions.h["!!" + event];
			if(f != null) {
				f();
				cnt = 1;
			}
			f = this.actions.h["!" + this.currentState];
			if(f != null) {
				f();
				++cnt;
			}
			f = this.actions.h["!*"];
			if(f != null) {
				f();
				++cnt;
			}
			if(cnt == 0) {
				f = this.actions.h["!!!"];
				if(f != null) {
					f();
				}
			}
		}
		this.src = "";
		this.evt = "";
		this.processingEvent = false;
		if(this.pendingEvent != "") {
			var e = this.pendingEvent;
			this.pendingEvent = "";
			this.send(e);
		}
	}
};
var EventsTest = $hxEnums["EventsTest"] = { __ename__ : true, __constructs__ : ["E1","E2","E3"]
	,E1: ($_=function(params) { return {_hx_index:0,params:params,__enum__:"EventsTest",toString:$estr}; },$_.__params__ = ["params"],$_)
	,E2: ($_=function(params) { return {_hx_index:1,params:params,__enum__:"EventsTest",toString:$estr}; },$_.__params__ = ["params"],$_)
	,E3: ($_=function(params) { return {_hx_index:2,params:params,__enum__:"EventsTest",toString:$estr}; },$_.__params__ = ["params"],$_)
};
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	var machine = new Machine("init");
	var e = EventsTest.E1();
	console.log("src/Main.hx:50:",$hxEnums[e.__enum__].__constructs__[e._hx_index]);
	var e = EventsTest.E1();
	machine.transitions.h[$hxEnums[e.__enum__].__constructs__[e._hx_index] + "###" + "init"] = "e1";
	var e = EventsTest.E1();
	machine.transitions.h[$hxEnums[e.__enum__].__constructs__[e._hx_index] + "###" + "e1"] = "e2";
	var e = EventsTest.E1();
	machine.transitions.h[$hxEnums[e.__enum__].__constructs__[e._hx_index] + "###" + "e2"] = "e3";
	var fn = function() {
		switch(machine.currentState) {
		case "e1":case "e2":case "e3":
			var _g = machine.currentEvt;
			switch(_g._hx_index) {
			case 0:
				var _g1 = _g.params;
				if(_g1 != null) {
					console.log("src/Main.hx:68:",_g1.a);
				}
				break;
			case 1:
				break;
			case 2:
				break;
			}
			break;
		}
	};
	machine.actions.h[">*"] = fn;
	var evt = EventsTest.E1({ a : 1000});
	machine.currentEvt = evt;
	machine.send($hxEnums[evt.__enum__].__constructs__[evt._hx_index]);
	console.log("src/Main.hx:82:",machine.currentState);
	var evt = EventsTest.E1({ a : 2000});
	machine.currentEvt = evt;
	machine.send($hxEnums[evt.__enum__].__constructs__[evt._hx_index]);
	console.log("src/Main.hx:89:",machine.currentState);
	var evt = EventsTest.E1({ a : 3000});
	machine.currentEvt = evt;
	machine.send($hxEnums[evt.__enum__].__constructs__[evt._hx_index]);
	console.log("src/Main.hx:96:",machine.currentState);
};
Math.__name__ = true;
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = true;
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var n = e.__constructs__[o._hx_index];
			var con = e[n];
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
Main.main();
})({});
